### ISSUE TITLE
[PHP] Highlighting `new` keyword

### ISSUE THREAD

**Issue by OskarStark** [scrivo/highlight.php#100]
We render the following code snippet in the Symfony-Docs like:
![CleanShot 2022-11-23 at 23 42 08@2x](https://user-images.githubusercontent.com/995707/203658177-e17d44a6-4928-4375-8675-29beb4b2ac9f.png)

[Link](https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#story-pools)

In this case `new` is a static method and should not be highlighted this way.

Could this be fixed? I am open to provide a PR if you can point me to the right direction.

Thanks

**Comment by allejo** [comment]
This issue has _probably_ been fixed in highlight.js' latest language definition but this project is severely behind in porting language definitions and new features. Converting the latest hljs language definition and using it in the current release of hlphp _might_ work for you but no guarantees!

**Comment by OskarStark** [comment]
Ok thank you

cc @wouterj @javiereguilaz @xabbuh (Symfony-Docs Team)
cc @kbond (Creator of Foundry)

**Comment by allejo** [comment]
This project has been on the back burner for me for a while because of difficult API changes in hljs but I would like to get a new release out that brings hlphp on par with hljs hopefully in Q1 of 2023.
