### ISSUE TITLE
php comments

### ISSUE THREAD

**Issue by nam-co** [scrivo/highlight.php#104]
Thanks for the package, in many ways is better to hable code with php than js, Im having some problems hope you can help me, I trying this code but it doesn't divide into tags anything

```
<code class="hljs php">
// Instantiate the Highlighter.
$hl = new \Highlight\Highlighter();
$code = file_get_contents('some_ruby_script.rb');
</code>
```

<img width="486" alt="Screenshot 2023-02-07 at 9 08 28 AM" src="https://user-images.githubusercontent.com/3951529/217267871-284520cb-e290-4d13-a595-7ae0214de3fb.png">

**Comment by nam-co** [comment]
Hope you can help me

**Comment by nam-co** [comment]
<img width="486" alt="Screenshot 2023-02-07 at 9 08 28 AM" src="https://user-images.githubusercontent.com/3951529/217268143-6e0287b9-d061-4769-854b-e514526722d8.png">

**Comment by S1SYPHOS** [comment]
I don't see any `echo` statement? 🤔

**Comment by nam-co** [comment]
the echo is fine, for other codes it works, please see the first image, that's the render (echo) Im getting

**Comment by S1SYPHOS** [comment]
I'm sorry, but all provided examples aren't even valid PHP code, no opening / closing brackets, no `echo` statement (or shorthand thereof), I just can't reproduce your problem!

Please provide a complete code example, which version you are using, etc 🙃

**Comment by S1SYPHOS** [comment]
Also, just from an image, I can't tell you what went wrong. Please post your example markup (= the code being rendered by PHP)!
