### ISSUE TITLE
Which language can I use to highlight the command line?

### ISSUE THREAD

**Issue by kk8686** [scrivo/highlight.php#11]
I want to highlint the command and params such as the fllowing contents

```cli
php test.php
php -r "echo 123"
mkdir test-dir
rm -rf test-dir
...more commands
```

I can't find it json in the path of "scrivo\highlight.php\Highlight\languages"

**Comment by cebe** [comment]
> I want to highlint the command and params such as the fllowing contents

you can use `bash`,`sh` or `zsh`. https://github.com/scrivo/highlight.php/blob/master/Highlight/languages/bash.json

**Comment by kk8686** [comment]
@cebe thanks

**Comment by samdark** [comment]
If it's solved, close the issue please.
