### ISSUE TITLE
"Invalid" regular expressions in registered languages broke autodetection

### ISSUE THREAD

**Issue by allejo** [scrivo/highlight.php#15]
In our Language class, we have a `langRe()` method, which is tasked with putting together our regular expressions.

https://github.com/scrivo/highlight.php/blob/a4930dde24bf6b9064fb52c22d71211144567e7f/Highlight/Language.php#L108-L111

As I was rewriting the unit tests, I noticed that the language files for **1c** and **ada** contained the following two regular expressions:

- `\d{4}([\.\\/:-]?\d{2}){0,5}` <- the `/` is treated as a delimiter
- `[]{}%#'"` <- the `[` and `]` aren't escaped

Since our method isn't very smart, putting these two regular expressions in between `/` caused `E_ERROR`s to be thrown. If these languages are registered in Highlighter for autodetection, then it'll fail due to the `E_ERROR`.

I manually modified the language files for the affected languages and tagged 9.12.0.1, but this needs a better solution. I'd be opposed to having to manually modify the language files since they're generated directly from highlight.js, so I'd favor improving our regex building in the Language class. Thoughts? Any better solutions?

/cc @S1SYPHOS 

**Edit:** We could also add another round of patches to our *get_language_definitions.php* file, too I guess...

**Comment by S1SYPHOS** [comment]
Not really, except .. merry christmas!

**Comment by allejo** [comment]
Merry Christmas! 😄

**Comment by Sommerregen** [comment]
Hi @allejo and @S1SYPHOS ,

First of all happy new year! And second sorry that I chime in here. Regarding your issue `addcslashes($value, '/')` is your friend. It escapes all slashes, if not already done. The string can then be safely used in a regex :-D.

Another minor issue and only if you are interested in. I'd like to see this library more memory friendly. Currently, it loads all languages into memory. IMO this shouldn't be. In the first stage, only the language names and their aliases are needed. Loading the respective language rules should be done dynamically upon request. What do you think?

Kind regards,
Benny

**Comment by S1SYPHOS** [comment]
Thanks for the suggestion, and also your kind words. As you can see (especially throughout this issue), we are damn happy people around here - even more so if a PR comes our way 👍

**Comment by Sommerregen** [comment]
Oh, great! 😄 Are you two the new maintainers of the project? And do already have plans for this project?

**Comment by allejo** [comment]
> First of all happy new year! And second sorry that I chime in here. Regarding your issue addcslashes($value, '/') is your friend. It escapes all slashes, if not already done. The string can then be safely used in a regex :-D.

Oh no, welcome and happy new year! As s1syphos said, we're happy to have people around. Using `addcslashes` seems promising and worth a try.

> Another minor issue and only if you are interested in. I'd like to see this library more memory friendly. Currently, it loads all languages into memory. IMO this shouldn't be. In the first stage, only the language names and their aliases are needed. Loading the respective language rules should be done dynamically upon request. What do you think?

I've experimented with lazy loading languages in the Highlighter before, but the time difference was surprisingly negligible. However, I didn't check the memory differences so I'd be open to revisiting it and adding lazy loading for memory improvements.

> Are you two the new maintainers of the project?

Yup, that's us!

> And do already have plans for this project?

Nothing really laid out but we're open to suggestions. I've just slowly been reorganizing/cleaning things up a tad.

**Comment by Sommerregen** [comment]
Alright and thanks for the friendly welcome 😄 

> I've experimented with lazy loading languages in the Highlighter before, but the time difference was surprisingly negligible. However, I didn't check the memory differences so I'd be open to revisiting it and adding lazy loading for memory improvements.
Yes, the time differences are negligible, but it is possible to save ~10 MB of memory. A huge difference and the payload of the Highlighter is then even smaller at around 1-2 MB. Please have a look at my PR #16.

My PR also addresses this issue here, reformat the code, adds doc blocks and sticks to modern coding conventions. I hope there is no issue with that and you guys are willing to merge it.
