### ISSUE TITLE
demo/line-numbers.php error

### ISSUE THREAD

**Issue by truefriend-cz** [scrivo/highlight.php#31]
demo/line-numbers.php ended error:
Parse error: syntax error, unexpected end of file in demo\line-numbers.php on line 94

Do you can fix?

**Comment by allejo** [comment]
Can you see if 7880e22 fixed your problem? I *think* that parse error might have been caused because of an accidental short tag.

**Comment by truefriend-cz** [comment]
Yes. It is fixed. Thanks for speedy reply 👍

**Comment by allejo** [comment]
awesome! first try too 🙌
