### ISSUE TITLE
Line numbers demo doesn't work with multi-line comments

### ISSUE THREAD

**Issue by gregsullivan** [scrivo/highlight.php#42]
I know that line numbers aren't officially supported by this project, but I wanted to flag that the line numbers demo fails on multi-line comments: Because the `<span>` tag wraps multiple lines, only the first line of the comment is properly styled once those lines are then placed in table cells.

Is there a way around this? If each line of the comment were wrapped in a `<span>` tag instead of the comment in its entirety, that would solve the problem, for example.

**Comment by allejo** [comment]
Welp, that makes sense. Take a look at 519578a42ac72181291a8226b805cdc372b3f9b0 as a possible quick fix. I'll revisit this later when I get more time.

**Comment by gregsullivan** [comment]
Thanks for your quick response! I'd been trying something similar, but this approach runs into problems when there's a doctag inside the comment. (Because there's a nested span, preg_replace picks up the closing tag of the child span.)

I'm starting to suspect an HTML parser might be the next step. (Or some increasingly clever use of preg_replace!)

**Comment by allejo** [comment]
Do you have a code snippet that I can use to replicate the nested spans?

**Comment by gregsullivan** [comment]
Definitely! Running this through the PHP highlighter:

```
/**
 * Enqueue styles for the block-based editor.
 *
 * @since Twenty Sixteen 1.6
 */
```

gives this:

```
<span class="hljs-comment">/**
 * Enqueue styles for the block-based editor.
 *
 * <span class="hljs-doctag">@since</span> Twenty Sixteen 1.6
 */</span>
```

**Comment by allejo** [comment]
Increasing the complexity of the regex does not bode well especially since multi-line strings are possible as well. Guess it's time to bring in an HTML parser 😕

Give 2a3ac770594046d381fc041ff351866d3883989d a try. Because of the added complexity, looks like have a utility based class or standalone project for this will be necessary for convenience.

**Comment by gregsullivan** [comment]
This works perfectly for me! I tested using a longer PHP function with many doctags nested within a multiline comment, and it succeeded without issue.

Thanks for addressing this so quickly!
