### ISSUE TITLE
Use the phrase "Syntax highlighting"

### ISSUE THREAD

**Issue by cup** [scrivo/highlight.php#60]
I was searching for projects like this using:

~~~
syntax highlighting in:readme
~~~

and I totally missed this project as the readme actually doesnt have the phrase "syntax highlighting" or even "syntax", as shown here:

https://en.wikipedia.org/wiki/Syntax_highlighting

and even here:

https://github.com/scrivo/highlight.php/blob/master/CONTRIBUTING.md

I think this would help with people looking for projects like this

**Comment by cup** [comment]
Here is something I found:

https://github.com/scrivo/highlight.php

**Comment by allejo** [comment]
Welp... Can't say I ever noticed that in our README :sweat_smile:
