### ISSUE TITLE
script tag not highlighted

### ISSUE THREAD

**Issue by subdesign** [scrivo/highlight.php#89]
Hi,
any idea why the starting script tag isn't highlighted for me? 

<img width="378" alt="Screenshot 2021-05-25 at 17 01 27" src="https://user-images.githubusercontent.com/691695/119936469-8b189180-bf89-11eb-9097-54dd155819ab.png">

could be a markdown thing (image)?
<img width="258" alt="Screenshot 2021-05-25 at 17 06 20" src="https://user-images.githubusercontent.com/691695/119936565-a8e5f680-bf89-11eb-8cf8-f05db4873057.png">

I use the github.css in this examlpe. And, eg. opening php tag ( <?php ) highlighted well. Strange..
The package I use for that is https://github.com/spatie/commonmark-highlighter

**Comment by taufik-nurrohman** [comment]
It is actually JS in a HTML, so the correct language would be `html` or `xml`.

**Comment by subdesign** [comment]
Thank you, it works!
