### ISSUE TITLE
Dynamic properties are deprecated in PHP 8.2

### ISSUE THREAD

**Issue by markseuffert** [scrivo/highlight.php#99]
Hi, I tested the highlighter with PHP 8.2 today and found two potential issues.

Code in `Highlighter::__construct()` initialises two properties which don't exist in class `RegExMatch`:

```
$this->lastMatch = new RegExMatch(array());
$this->lastMatch->type = "";
$this->lastMatch->rule = null;
```

Code in `Terminators::exec()` initialises another property `RegExMatch::extra`, but apparently is never used:

```
$match->extra = array($this->mode->illegal, $this->mode->terminator_end);
```

Let me know if you need more information. Thanks for investigating.

**Comment by allejo** [comment]
I totally kept thinking to myself, "PHP 8.2 is still a ways away, I've got time to fix it." I completely forgot that it's PHP release season... I'll get this fixed and shipped by this weekend 👍

**Comment by allejo** [comment]
Sorry about the delay! It's been an exhausting few weeks 😓 

I've tagged https://github.com/scrivo/highlight.php/releases/tag/v9.18.1.10 and have added unit testing for PHP 8.0 - 8.2
